behaviors:
  VampireAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5.0e6
    time_horizon: 64
    summary_freq: 20000
    threaded: true

environment_parameters:
  # Example curriculum hooks; adjust as needed
  difficulty:
    curriculum:
      - name: easy
        value: 0.2
        completion_criteria:
          behavior: VampireAgent
          measure: reward
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 200
      - name: medium
        value: 0.5
        completion_criteria:
          behavior: VampireAgent
          measure: reward
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 400
      - name: hard
        value: 0.8
